jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: GitHub Readme Stats Action
        uses: stats-organization/github-readme-stats-action@v1.1.0
        with:
          # Specify which card you want: "stats", "languages", or "repo"
          card: "stats" 
          # You usually need to provide your GitHub Token to fetch data
          gh_token: ${{ secrets.GITHUB_TOKEN }}
